name: StreamLy CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm ci

    - name: Backend Typecheck
      working-directory: ./backend
      run: npx tsc --noEmit

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Frontend Typecheck
      working-directory: ./frontend
      run: npx tsc --noEmit
